In [2]:
import sympy as sp
from sympy.interactive.printing import init_printing
init_printing(use_unicode=False, wrap_line=False)
import numpy as np
import math
from run import NCV

In [11]:
T = sp.symbols('T')
F = sp.Matrix([[0, 1],[0, 0]])
Fi = sp.exp(F*T)
Fi

[1  T]
[    ]
[0  1]

In [33]:
q = 1
T = 1
T, q = sp.symbols('T q')
F = sp.Matrix([[0, 1],[0, 0]])
Fi = sp.exp(F*T)
L = sp.Matrix([[0], [1]])
Q = sp.integrate( (Fi*L)*q*(Fi*L).T, (T, 0, T) )
Q

[ 3     2  ]
[T *q  T *q]
[----  ----]
[ 3     2  ]
[          ]
[ 2        ]
[T *q      ]
[----  T*q ]
[ 2        ]

In [34]:
np.array(Q)

array([[T**3*q/3, T**2*q/2],
       [T**2*q/2, T*q]], dtype=object)

In [29]:
T,q = sp.symbols('T q')
F = sp.Matrix(np.zeros((2,2)))
L = sp.Matrix([[1,0], [0,1]])
Fi = sp.exp(F*T)
Q = sp.integrate( (Fi*L)*q*(Fi*L).T, (T, 0, 1) )
Q

D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The MathtextBackendBitmap 

[q  0]
[    ]
[0  q]

In [17]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
sp.Matrix(np.zeros((2,2)))

D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The MathtextBackendBitmap 

[0  0]
[    ]
[0  0]

In [38]:
F = sp.Matrix(np.vstack((np.array([[0,0,1,0],[0,0,0,1]]), np.zeros((2,4)))))
F

[0  0  1.0   0 ]
[              ]
[0  0   0   1.0]
[              ]
[0  0   0    0 ]
[              ]
[0  0   0    0 ]

In [39]:
L = sp.Matrix(np.vstack((np.zeros((2,2)), np.eye(2))))
L

D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The MathtextBackendBitmap 

[ 0    0 ]
[        ]
[ 0    0 ]
[        ]
[1.0   0 ]
[        ]
[ 0   1.0]

In [42]:
sp.Matrix(np.vstack((np.zeros((4,2)), np.eye(2))))

D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The MathtextBackendBitmap 

[ 0    0 ]
[        ]
[ 0    0 ]
[        ]
[ 0    0 ]
[        ]
[ 0    0 ]
[        ]
[1.0   0 ]
[        ]
[ 0   1.0]

In [47]:
N = 40
v = np.linspace(5 * math.pi, 0, N)
x = np.cos(v) * v
y = np.sin(v) * v
vx = np.diff(x)
vx = np.insert(vx, 0, 0)
vy = np.diff(y)
vy = np.insert(vy, 0, 0)

vx

[ 1.62749851e+00  3.75719087e+00  5.18162417e+00  5.70927426e+00
  5.30294363e+00  4.07815282e+00  2.27657181e+00  2.20036509e-01
 -1.74632105e+00 -3.31186894e+00 -4.24953850e+00 -4.44840633e+00
 -3.92518224e+00 -2.81376709e+00 -1.33579494e+00  2.41841243e-01
  1.65456172e+00  2.68437903e+00  3.19348766e+00  3.14199625e+00
  2.58765627e+00  1.66869561e+00  5.73772728e-01 -4.94872109e-01
 -1.35810590e+00 -1.88986884e+00 -2.03541365e+00 -1.81520912e+00
 -1.31466053e+00 -6.62413058e-01 -1.99540843e-03  5.37415086e-01
  8.65424438e-01  9.45539513e-01  7.98447472e-01  4.93342186e-01
  1.29543994e-01 -1.87476259e-01 -3.70538546e-01]


array([ 0.00000000e+00,  1.62749851e+00,  3.75719087e+00,  5.18162417e+00,
        5.70927426e+00,  5.30294363e+00,  4.07815282e+00,  2.27657181e+00,
        2.20036509e-01, -1.74632105e+00, -3.31186894e+00, -4.24953850e+00,
       -4.44840633e+00, -3.92518224e+00, -2.81376709e+00, -1.33579494e+00,
        2.41841243e-01,  1.65456172e+00,  2.68437903e+00,  3.19348766e+00,
        3.14199625e+00,  2.58765627e+00,  1.66869561e+00,  5.73772728e-01,
       -4.94872109e-01, -1.35810590e+00, -1.88986884e+00, -2.03541365e+00,
       -1.81520912e+00, -1.31466053e+00, -6.62413058e-01, -1.99540843e-03,
        5.37415086e-01,  8.65424438e-01,  9.45539513e-01,  7.98447472e-01,
        4.93342186e-01,  1.29543994e-01, -1.87476259e-01, -3.70538546e-01])

In [6]:
T = sp.symbols('T')
q = 1
F = sp.Matrix(np.vstack((np.array([[0,0,1,0],[0,0,0,1]]), np.zeros((2,4)))))
L = sp.Matrix(np.vstack((np.zeros((2,2)), np.eye(2))))
Fi = sp.exp(F*T)
Q = sp.integrate( (Fi*L)*q*(Fi*L).T, (T, 0, 1) )

In [9]:
F

D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
D:\anaconda3\envs\ids\lib\site-packages\IPython\lib\latextools.py:126: MatplotlibDeprecationWarning: 
The MathtextBackendBitmap 

[0  0  1.0   0 ]
[              ]
[0  0   0   1.0]
[              ]
[0  0   0    0 ]
[              ]
[0  0   0    0 ]

In [16]:
o = np.ones((4,4))
o[:,:2]

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])